version: 0.2 
env: 
  variables: 
    AWS_REG: "eu-west-1" 
    KIUWAN_APP_NAME: "builderhook" 
  parameter-store: 
    AWS_ACCOUNT_ID: "dev-AWS_ACCOUNT-ID" 
    KIUWAN_USER: "dev-kiuwan_user" 
    KIUWAN_PASSWORD: "dev-kiuwan_password" 
phases: 
  install: 
    commands: 
      - apt-get -y update 
      - apt-get -y install apt-transport-https ca-certificates 
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - 
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable" 
      - apt-get -y update 
      - apt-get install -y docker-ce 
      - service docker start 
      - $(aws ecr get-login --no-include-email --region $AWS_REGION) 
      - docker pull 708382520005.dkr.ecr.eu-west-1.amazonaws.com/kiuwan:latest 
      - echo $CODEBUILD_SRC_DIR 
      - docker run -v $CODEBUILD_SRC_DIR:/source_code 708382520005.dkr.ecr.eu-west-1.amazonaws.com/kiuwan:latest --softwarename $KIUWAN_APP_NAME --sourcePath /source_code --user $KIUWAN_USER --pass $KIUWAN_PASSWORD 
  build: 
    commands: 
        - echo "some command" 
  
  post_build: 
    commands: 
        - echo "some command" 
